# Problem 1

In [39]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

matrix = np.random.randint(0, 11, size=(5))
print(matrix)
# 3 - matris'in boyutunu öğrenin

print(matrix.shape)

# 4 - matris'i yeniden boyutlandırın

matrix = matrix.reshape(5,1)
print(matrix)

# 5 - matris'in boyut sayısını öğrenin
print(matrix.ndim)


[4 9 9 5 2]
(5,)
[[4]
 [9]
 [9]
 [5]
 [2]]
2


# Problem 2

In [55]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

matrix2 = np.arange(1, 11, 2)
print(matrix2)

# 2 - Oluşturduğunuz matrisi parçalayın

a,b,c = np.split(matrix2, [1,2])
print(a)
print(b)
print(c)

# 3 - Parçalanmış matrisleri birleştirin

matrix_abc = np.concatenate([a,b,c])
print(matrix_abc)

[1 3 5 7 9]
[1]
[3]
[5 7 9]
[1 3 5 7 9]


# Problem 3

In [62]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

matrix3 = np.random.choice(np.arange(5, 101, 2), size=10)
print(matrix3)

# 2 - matris'in özelliklerini inceleyin

print(matrix3.ndim)
print(matrix3.shape)
print(matrix3.size)
print(matrix3.dtype)



[19 17 39 23 23 39 13 11 61 79]
1
(10,)
10
int32
q 40
