# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun

a = np.array([84,17,62,46,25])
print(a)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.

sorted_a = np.sort(a)
print(sorted_a)

[84 17 62 46 25]
[17 25 46 62 84]


# Problem 2

In [33]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

b = np.array([10,15,30,45,60])
print(b)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

c = np.arange(5,15)
print(c)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

d = np.arange(50,100,5)
print(d)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

e = np.zeros(10)
print(e)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

f = np.ones(10)
print(f)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.

g = np.linspace(0,100,5)
print(g)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

h = np.random.randint(10,31, size=5)
print(h)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.

i = np.random.uniform(-1,1, 10)
print(i)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

j = np.random.randint(10,51,size=(3,5))
print(j)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

j_satir_toplami = np.sum(j, axis=1)
j_sutun_toplami = np.sum(j, axis=0)

print("j satırları toplamı: ", j_satir_toplami)
print("j sütunları toplamı: ", j_sutun_toplami)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

en_buyuk = np.max(j)
en_kucuk = np.min(j)
ortalama = np.mean(j)

print("j en büyük değer: ", en_buyuk, "\nj en küçük değer: ", en_kucuk, "\nj ortalama değer: ", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

j_en_buyuk_deger_index = np.argmax(j)
print("j en büyük değerinin indeksi: ", j_en_buyuk_deger_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

k = np.random.randint(10,21, size=8)
k_ilk_uc_eleman = k[:3]
print(k_ilk_uc_eleman)


# 14- Üretilen dizinin elemanlarını tersten yazdırın.

k = k[::-1]
print(k)

# 15- Üretilen matrisin ilk satırını seçiniz.

j_ilk_satir = k[0]
print(j_ilk_satir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

j_ikinci_satir_ucuncu_sutun = j[1,2]
print(j_ikinci_satir_ucuncu_sutun)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

j_butun_satirlar_ilk_eleman = j[:,0]
print(j_butun_satirlar_ilk_eleman)

# 18- Üretilen matrisin her bir elemanının karesini alınız.

kareler = j ** 2
print("Kareler:\n ", kareler)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

l = np.arange(-50,51)
l_pozitif_cift_sayilar =l[(l > 0) & (l % 2 == 0)]
print("l pozitif çift sayılar: ", l_pozitif_cift_sayilar)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[25 24 22 29 18]
[ 0.31653004  0.55291951 -0.21337575  0.62976751  0.63422364 -0.46404313
  0.31448035 -0.6076516  -0.09526943  0.19988868]
[[34 15 23 16 17]
 [29 41 47 15 47]
 [34 32 24 44 32]]
j satırları toplamı:  [105 179 166]
j sütunları toplamı:  [97 88 94 75 96]
j en büyük değer:  47 
j en küçük değer:  15 
j ortalama değer:  30.0
j en büyük değerinin indeksi:  7
[12 15 11]
[14 14 11 19 14 11 15 12]
14
47
[34 29 34]
Kareler:
  [[1156  225  529  256  289]
 [ 841 1681 2209  225 2209]
 [1156 1024  576 1936 1024]]
l pozitif çift sayılar:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
